name: Deploy MultiK8s
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true cygnetops/react-test npm test
      
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-387811

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c
      
      - name: Build
        run: |-
          docker build -t stephengrider/multi-client:latest -t stephengrider/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t cygnetops/multi-server-pgfix-5-11:latest -t stephengrider/multi-server-pgfix-5-11:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t stephengrider/multi-worker:latest -t stephengrider/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push luqmanfak/multi-client:latest
          docker push luqmanfak/multi-server:latest
          docker push luqmanfak/multi-worker:latest

          docker push luqmanfak/multi-client:${{ env.SHA }}
          docker push luqmanfak/multi-server:${{ env.SHA }}
          docker push luqmanfak/multi-worker:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=cygnetops/multi-server-pgfix-5-11:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=stephengrider/multi-client:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=stephengrider/multi-worker:${{ env.SHA }}












